# Generated by Django 5.1.3 on 2025-04-29 11:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='plansubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantype', models.CharField(default='Starter', max_length=100, verbose_name='plan type')),
                ('percent', models.IntegerField(default=10, verbose_name='plan percentage')),
                ('price', models.IntegerField(default='50', verbose_name='plan price to pay')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100, verbose_name='user password')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='if this account is disabled')),
                ('country', models.CharField(max_length=1000, verbose_name='user country')),
                ('Verified', models.BooleanField(default=False, verbose_name='if the user is verified')),
                ('user_token', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='user token')),
                ('phone_number', models.CharField(max_length=50, verbose_name='user mobile number')),
                ('is_edit', models.BooleanField(default=False, verbose_name='if the user have edited ')),
                ('account_type', models.CharField(choices=[('General', 'General'), ('Admin', 'Admin')], default='General', max_length=200, null=True, verbose_name='the account type')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='the date time account was created')),
                ('ip_adress', models.GenericIPAddressField(blank=True, null=True, verbose_name='user ip adress')),
                ('reflink', models.URLField(blank=True, null=True, unique=True, verbose_name='user referral link')),
                ('refered_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='your refferal')),
                ('referral_count', models.IntegerField(default=0, verbose_name='total referials')),
                ('c_code', models.CharField(blank=True, max_length=11, null=True, verbose_name='user country code')),
                ('user_browser', models.CharField(blank=True, max_length=200, null=True, verbose_name='user browser access')),
                ('user_device', models.CharField(blank=True, max_length=200, null=True, verbose_name='user access device')),
                ('qr_code', models.ImageField(blank=True, null=True, unique=True, upload_to='qrcodes', verbose_name='user qrcode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.IntegerField(default=0, verbose_name='user total balance')),
                ('total_earn', models.IntegerField(default=0, verbose_name='total earning')),
                ('total_invest', models.IntegerField(default=0, verbose_name='total investments')),
                ('total_with', models.IntegerField(default=0, verbose_name='total withdrawal')),
                ('bit_wallet', models.CharField(blank=True, max_length=200, null=True, verbose_name='bitcoin wallet address')),
                ('lit_wallet', models.CharField(blank=True, max_length=200, null=True, verbose_name='litecoin wallet address')),
                ('eth_wallet', models.CharField(blank=True, max_length=200, null=True, verbose_name='etherum wallet address')),
                ('tron_wallet', models.CharField(blank=True, max_length=200, null=True, verbose_name='tron wallet address')),
                ('trc20_wallet', models.CharField(blank=True, max_length=200, null=True, verbose_name='trc20 wallet address')),
                ('erc20_wallet', models.CharField(blank=True, max_length=200, null=True, verbose_name='erc20 wallet address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptoriseapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_typ', models.CharField(max_length=100, verbose_name='transaction type')),
                ('amount', models.IntegerField(default=0, verbose_name='transation amount')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date and time of the transaction')),
                ('status', models.CharField(max_length=100, verbose_name='transaction status')),
                ('accont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptoriseapp.account')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='userimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pics', models.ImageField(blank=True, upload_to='user profile', verbose_name='user image')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptoriseapp.profile')),
            ],
        ),
    ]
