# Generated by Django 5.1.3 on 2025-04-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoriseapp', '0003_alter_profile_id_newfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(default='5b925', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
