# Generated by Django 5.1.3 on 2025-04-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoriseapp', '0004_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(default='mnom3', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
