# Generated by Django 5.1.3 on 2025-04-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoriseapp', '0005_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfile',
            name='c_code',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='user country code'),
        ),
        migrations.AddField(
            model_name='newfile',
            name='ip_adress',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='user ip adress'),
        ),
        migrations.AddField(
            model_name='newfile',
            name='phone_number',
            field=models.CharField(default='+1', max_length=50, verbose_name='user mobile number'),
        ),
        migrations.AddField(
            model_name='newfile',
            name='place',
            field=models.CharField(default='United states', max_length=1000, verbose_name='user country'),
        ),
        migrations.AddField(
            model_name='newfile',
            name='user_browser',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='user browser access'),
        ),
        migrations.AddField(
            model_name='newfile',
            name='user_device',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='user access device'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
