# Generated by Django 5.1.3 on 2025-04-29 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoriseapp', '0006_newfile_c_code_newfile_ip_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfile',
            name='account_type',
            field=models.CharField(choices=[('General', 'General'), ('Admin', 'Admin')], default='General', max_length=200, null=True, verbose_name='the account type'),
        ),
        migrations.AddField(
            model_name='newfile',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='the date time account was created'),
        ),
        migrations.AddField(
            model_name='newfile',
            name='is_edit',
            field=models.BooleanField(default=False, verbose_name='if the user have edited '),
        ),
        migrations.AddField(
            model_name='newfile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='qrcodes', verbose_name='user qrcode'),
        ),
        migrations.AddField(
            model_name='newfile',
            name='refered_from',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='your refferal'),
        ),
        migrations.AddField(
            model_name='newfile',
            name='referral_count',
            field=models.IntegerField(default=0, verbose_name='total referials'),
        ),
        migrations.AddField(
            model_name='newfile',
            name='reflink',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='user referral link'),
        ),
        migrations.AddField(
            model_name='newfile',
            name='user_token',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='user token'),
        ),
    ]
