# Generated by Django 5.1.3 on 2025-04-29 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoriseapp', '0007_newfile_account_type_newfile_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptoriseapp.newfile'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptoriseapp.newfile'),
        ),
    ]
