# Generated by Django 5.1.3 on 2025-04-29 21:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoriseapp', '0008_alter_account_user_alter_userimage_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='deposite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='deposite amount')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date and time of the transaction')),
                ('machant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptoriseapp.newfile')),
            ],
        ),
        migrations.CreateModel(
            name='withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='deposite amount')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date and time of the transaction')),
                ('machant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptoriseapp.newfile')),
            ],
        ),
    ]
