# Generated by Django 5.1.3 on 2025-04-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoriseapp', '0009_deposite_withdraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_price', models.CharField(max_length=100, null=True, verbose_name='btcprice')),
                ('ltc_price', models.CharField(max_length=100, null=True, verbose_name='ltcprice')),
                ('eth_price', models.CharField(max_length=100, null=True, verbose_name='ethprice')),
            ],
        ),
    ]
