# Generated by Django 5.1.3 on 2025-04-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoriseapp', '0010_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='user wallet adress'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='coin',
            field=models.CharField(max_length=100, null=True, verbose_name='cointype'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='network',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='network type'),
        ),
    ]
